#!/bin/bash

mkdir -p ./english/root/app

rsync -r --exclude='.git' --exclude='platforms' --exclude='plugins' --exclude='node_modules' --exclude='containers' --delete-excluded ../ ./english/root/app

