#!/usr/bin/env bash

CONTAINER=english

docker build -t friend/$CONTAINER english/ && (
    docker rm -f $CONTAINER
    docker run -itd --name $CONTAINER \
        $ADDITIONAL_DOCKER_ARGS \
        --restart=always \
        -p 8100:80 \
        -v /opt/containers:/opt/containers:ro \
        -v /opt/containers/$CONTAINER:/opt/containers/$CONTAINER \
        -v /var/log/containers/$CONTAINER:/var/log \
        friend/$CONTAINER
)

